---
name-template: 'Galeria: v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - 'pr:feat'
      - 'pr:breaking-change'
  - title: '🐞 Bug Fixes'
    labels:
      - 'pr:fix'
  - title: '🔧 Maintenance'
    label: 
      - 'pr:chore'
      - 'pr:refactor'
      - 'pr:build'
      - 'pr:ci'
      - 'pr:docs'
      - 'pr:style'
      - 'pr:revert'
      - 'pr:test'
      - 'pr:perf'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'pr:breaking-change'
  minor:
    labels:
      - 'pr:feat'
  patch:
    labels:
      - 'pr:fix'
      - 'pr:chore'
      - 'pr:refactor'
      - 'pr:build'
      - 'pr:ci'
      - 'pr:docs'
      - 'pr:style'
      - 'pr:revert'
      - 'pr:test'
      - 'pr:perf'
      
  default: patch
template: |
  ## Changes on $REPOSITORY

  $CHANGES
autolabeler:
  - label: 'pr:breaking-change'
    body: '/breaking change/i'
    title: '/breaking change/i'
  - label: 'pr:feat'
    title: '/^feat/i'
  - label: 'pr:fix'
    title: '/^fix/i'
  - label: 'pr:chore'
    title: '/^chore/i'
  - label: 'pr:refactor'
    title: '/^refactor/i'
  - label: 'pr:build'
    title: '/^build/i'
  - label: 'pr:ci'
    title: '/^ci/i'
  - label: 'pr:docs'
    title: '/^docs/i'
  - label: 'pr:style'
    title: '/^style/i'
  - label: 'pr:revert'
    title: '/^revert/i'
  - label: 'pr:test'
    title: '/^test/i'
  - label: 'pr:perf'
    title: '/^perf/i'