name: Generate new release
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
permissions:
  contents: read

jobs:
  update_release_draft:
    name: Generate Release version by release-drafter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.conf.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
